services:
  web:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "8082:8082"
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"


